- name: install nginx
  yum: name=nginx

- name: start nginx
  service: name=nginx state=started enabled=yes

- name: copy /etc/nginx/
  copy: src=etc/nginx/ dest=/etc/nginx/ backup=yes
  notify: restart nginx

- name: template by nginx default.conf
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: copy /usr/share/nginx/html/
  copy: src=usr/share/nginx/html/ dest=/usr/share/nginx/html/ backup=yes

## Common Conifgration ( CloudWatch Logs & Datadog Integration & logrotate )
- name: copy /etc/awslogs/config/
  copy: src=etc/awslogs/config/ dest=/etc/awslogs/config/ backup=yes
  notify: restart awslogs agent

- name: copy /etc/etc/dd-agent/
  copy: src=etc/dd-agent/ dest=/etc/dd-agent/ backup=yes
  when: datadog == "true"
  notify: restart datadog-agent

- name: copy /etc/logrotate.d/
  copy: src=/etc/logrotate.d/ dest=/etc/logrotate.d/
