- name: yum install for MonitoringTools command
  yum: name={{ item }} state=latest
  with_items:
    - nrpe
    - nagios-plugins-nrpe
    - nagios-plugins-all

- name: Add nrpe plugin for check_log* check_memory
  copy: src={{ item }} dest=/usr/lib64/nagios/plugins/ owner=root group=root mode=0755
  with_items:
    - check_log
    - check_log2
    - check_log3
    - check_memory

- name: (nrpe)
  template: src=nrpe.cfg dest=/etc/nagios/
  notify: restart nrpe
